[package]
name = "jupyterscrub"
version = "0.1.0"
edition = "2018"
authors = ["Tom Hunger"]
license = "Apache-2.0"
rust = "1.54"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
clap = "3.0"
serde_json = "1.0"
anyhow = "1.0"
